### ISSUE TITLE
graphene: FAILED: src/Graphene-1.0.gir 

### ISSUE THREAD

**Issue by tschoonj** [ebassi/graphene#92]
### Experienced behavior

I was trying to build gtk 3.89.2 and noticed that I didn't have the graphene-gobject library installed after rebuilding graphene 1.5.2 with your fix from #91. By the way, this library was not checked for during gtk+'s configure invocation, it only showed up as compile-time error when the graphene-gobject headers were not found...

I retried then after passing the required options to `meson` but ended up with the following errors:

````
[64/65] 'Generating Graphene-1.0.gir with a custom command.'
FAILED: src/Graphene-1.0.gir 
'/usr/local/opt/gobject-introspection/bin/g-ir-scanner' '../src/graphene-box.h' '../src/graphene-euler.h' '../src/graphene-frustum.h' '../src/graphene-macros.h' '../src/graphene-matrix.h' '../src/graphene-plane.h' '../src/graphene-point.h' '../src/graphene-point3d.h' '../src/graphene-quad.h' '../src/graphene-quaternion.h' '../src/graphene-ray.h' '../src/graphene-rect.h' '../src/graphene-size.h' '../src/graphene-sphere.h' '../src/graphene-triangle.h' '../src/graphene-types.h' '../src/graphene-vec2.h' '../src/graphene-vec3.h' '../src/graphene-vec4.h' '../src/graphene-version-macros.h' '../src/graphene-gobject.h' '../src/graphene-alloc.c' '../src/graphene-box.c' '../src/graphene-euler.c' '../src/graphene-frustum.c' '../src/graphene-matrix.c' '../src/graphene-plane.c' '../src/graphene-point.c' '../src/graphene-point3d.c' '../src/graphene-quad.c' '../src/graphene-quaternion.c' '../src/graphene-ray.c' '../src/graphene-rect.c' '../src/graphene-size.c' '../src/graphene-sphere.c' '../src/graphene-triangle.c' '../src/graphene-vectors.c' '../src/graphene-gobject.c' '-D_REENTRANT' '-I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include' '-I/usr/local/Cellar/pcre/8.39/include' '-I/usr/local/Cellar/glib/2.50.2/include/glib-2.0' '-I/usr/local/Cellar/glib/2.50.2/lib/glib-2.0/include' '-I/usr/local/opt/gettext/include' '-I/usr/local/Cellar/gobject-introspection/1.50.0/include/gobject-introspection-1.0' '--no-libtool' '--namespace=Graphene' '--nsversion=1.0' '--warn-all' '--output' 'src/Graphene-1.0.gir' '--identifier-filter-cmd=/private/tmp/graphene-20170101-3369-w6flsg/graphene-1.5.2/src/identfilter.py' '--c-include=graphene-gobject.h' '--accept-unprefixed' '-DGRAPHENE_COMPILATION' '--cflags-begin' '-I/private/tmp/graphene-20170101-3369-w6flsg/graphene-1.5.2/src' '-I/private/tmp/graphene-20170101-3369-w6flsg/graphene-1.5.2/build/src' '--cflags-end' '-I/private/tmp/graphene-20170101-3369-w6flsg/graphene-1.5.2/src' '-I/private/tmp/graphene-20170101-3369-w6flsg/graphene-1.5.2/build/src' '--include=GObject-2.0' '--symbol-prefix=graphene' '--identifier-prefix=Graphene' '--pkg-export=graphene-gobject-1.0' '-I/usr/local/opt/gettext/include' '-I/usr/local/Cellar/glib/2.50.2/include/glib-2.0' '-I/usr/local/Cellar/glib/2.50.2/lib/glib-2.0/include' '-I/usr/local/Cellar/pcre/8.39/include' '-L/private/tmp/graphene-20170101-3369-w6flsg/graphene-1.5.2/build/src' '-L/usr/local/opt/gettext/lib' '-L/usr/local/Cellar/glib/2.50.2/lib' '-lm' '-lglib-2.0' '-lintl' '-lgobject-2.0' '--library' 'graphene-1.0'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/signal.h:79: syntax error, unexpected identifier, expecting ')' in 'void (* _Nullable bsd_signal(int, void (* _Nullable)(int)))(int);' at 'bsd_signal'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/signal.h:79: syntax error, unexpected ')', expecting ',' or ';' in 'void (* _Nullable bsd_signal(int, void (* _Nullable)(int)))(int);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/signal.h:99: syntax error, unexpected identifier, expecting ')' in 'void (* _Nullable sigset(int, void (* _Nullable)(int)))(int);' at 'sigset'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/signal.h:99: syntax error, unexpected ')', expecting ',' or ';' in 'void (* _Nullable sigset(int, void (* _Nullable)(int)))(int);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/qos.h:113: syntax error, unexpected RESTRICT, expecting ')' or ',' in '  qos_class_t * _Nullable restrict __qos_class,' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/qos.h:114: syntax error, unexpected INT, expecting identifier or '(' or '*' in '  int * _Nullable restrict __relative_priority);' at 'int'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/qos.h:114: syntax error, unexpected ')', expecting ',' or ';' in '  int * _Nullable restrict __relative_priority);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/qos.h:185: syntax error, unexpected RESTRICT, expecting ')' or ',' in '  qos_class_t * _Nullable restrict __qos_class,' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/qos.h:186: syntax error, unexpected INT, expecting identifier or '(' or '*' in '  int * _Nullable restrict __relative_priority);' at 'int'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/qos.h:186: syntax error, unexpected ')', expecting ',' or ';' in '  int * _Nullable restrict __relative_priority);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:243: syntax error, unexpected '*', expecting ')' or ',' in '  void * _Nullable * _Nonnull restrict, size_t * restrict);' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:243: syntax error, unexpected ')', expecting identifier or '(' in '  void * _Nullable * _Nonnull restrict, size_t * restrict);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:247: syntax error, unexpected '*', expecting ')' or ',' in '  void * _Nullable * _Nonnull restrict);' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:295: syntax error, unexpected RESTRICT, expecting ')' or ',' in '  const pthread_condattr_t * _Nullable restrict)' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:304: syntax error, unexpected RESTRICT, expecting ')' or ',' in '  const struct timespec * _Nullable restrict)' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:326: syntax error, unexpected '*', expecting ')' or ',' in 'int pthread_create(pthread_t _Nullable * _Nonnull restrict,' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:327: syntax error, unexpected ',', expecting identifier or '(' or '*' or ';' in '  const pthread_attr_t * _Nullable restrict,' at ','
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:328: syntax error, unexpected '*' in '  void * _Nullable (* _Nonnull)(void * _Nullable),' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:328: syntax error, unexpected ')', expecting ',' or ';' in '  void * _Nullable (* _Nonnull)(void * _Nullable),' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:329: syntax error, unexpected ')', expecting identifier or '(' or '*' or ';' in '  void * _Nullable restrict);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:349: syntax error, unexpected RESTRICT, expecting ')' or ',' in 'int pthread_getschedparam(pthread_t , int * _Nullable restrict,' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:350: syntax error, unexpected ')', expecting identifier or '(' or '*' or ';' in '  struct sched_param * _Nullable restrict);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:353: syntax error, unexpected identifier, expecting ',' or ';' in 'void* _Nullable pthread_getspecific(pthread_key_t);' at 'pthread_getspecific'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:356: syntax error, unexpected '*', expecting ')' or ',' in 'int pthread_join(pthread_t , void * _Nullable * _Nullable)' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:374: syntax error, unexpected RESTRICT, expecting ')' or ',' in '  const pthread_mutexattr_t * _Nullable restrict);' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:432: syntax error, unexpected RESTRICT, expecting ')' or ',' in '  const pthread_rwlockattr_t * _Nullable restrict)' at 'restrict'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:529: syntax error, unexpected '*', expecting ')' or ',' in '  pthread_t _Nullable * _Nonnull, const pthread_attr_t * _Nullable,' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:530: syntax error, unexpected VOID, expecting identifier or '(' or '*' in '  void * _Nullable (* _Nonnull)(void * _Nullable), void * _Nullable);' at 'void'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:530: syntax error, unexpected '*' in '  void * _Nullable (* _Nonnull)(void * _Nullable), void * _Nullable);' at '*'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:530: syntax error, unexpected ')', expecting ',' or ';' in '  void * _Nullable (* _Nonnull)(void * _Nullable), void * _Nullable);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:530: syntax error, unexpected ')', expecting ',' or ';' in '  void * _Nullable (* _Nonnull)(void * _Nullable), void * _Nullable);' at ')'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread/pthread.h:540: syntax error, unexpected identifier in '_Nullable pthread_t pthread_from_mach_thread_np(mach_port_t);' at '_Nullable'
In file included from /private/tmp/graphene-20170101-3369-w6flsg/graphene-1.5.2/build/tmp-introspectxBnQzD/Graphene-1.0.c:2:
In file included from /usr/local/Cellar/glib/2.50.2/include/glib-2.0/glib.h:30:
In file included from /usr/local/Cellar/glib/2.50.2/include/glib-2.0/glib/galloca.h:32:
/usr/local/Cellar/glib/2.50.2/include/glib-2.0/glib/gtypes.h:423:3: error: '_GStaticAssertCompileTimeAssertion_0' declared as an array with a negative size
  G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/glib/2.50.2/include/glib-2.0/glib/gmacros.h:232:103: note: expanded from macro 'G_STATIC_ASSERT'
#define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                                                                      ^~~~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/usr/local/opt/gobject-introspection/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/local/Cellar/gobject-introspection/1.50.0/lib/gobject-introspection/giscanner/scannermain.py", line 544, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "/usr/local/Cellar/gobject-introspection/1.50.0/lib/gobject-introspection/giscanner/scannermain.py", line 419, in create_binary
    gdump_parser.get_error_quark_functions())
  File "/usr/local/Cellar/gobject-introspection/1.50.0/lib/gobject-introspection/giscanner/dumper.py", line 328, in compile_introspection_binary
    return dc.run()
  File "/usr/local/Cellar/gobject-introspection/1.50.0/lib/gobject-introspection/giscanner/dumper.py", line 167, in run
    introspection_obj = self._compile(c_path)
  File "/usr/local/Cellar/gobject-introspection/1.50.0/lib/gobject-introspection/giscanner/dumper.py", line 207, in _compile
    self._options.init_sections)
  File "/usr/local/Cellar/gobject-introspection/1.50.0/lib/gobject-introspection/giscanner/ccompiler.py", line 241, in compile
    source_str.rfind(os.sep)]))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile
    raise CompileError, msg
distutils.errors.CompileError: command 'clang' failed with exit status 1
ninja: build stopped: subcommand failed.
````

### Expected behavior

The gobject-introspection command to produce the Gir file, followed by a build of the graphene-object shared library.

### Steps to reproduce

On a Mac OS X El Capitan system (10.11.6) with Xcode 8.2.1 and an up-to-date Homebrew installation.
I am the maintainer of Homebrew's graphene Formula and used it to build graphene 1.5.2:

````ruby
class Graphene < Formula
  desc "Thin layer of graphic data types"
  homepage "https://ebassi.github.io/graphene/"
  url "https://download.gnome.org/sources/graphene/1.2/graphene-1.2.10.tar.xz"
  sha256 "e7b58334a91ae75b776fda987c29867710008673040fc996949933f2c5f17fdb"

  devel do
    url "https://download.gnome.org/sources/graphene/1.5/graphene-1.5.2.tar.xz"
    sha256 "4b2fe2c3aad43416bb520e2b3f0e1f4535b0fa722291a14904b01765afe9416f"
    depends_on "meson" => :build
    depends_on "ninja" => :build
  end

  bottle do
    sha256 "fe4ea086531c7c99ac358bc5dcf7017dee230530cbb1c9ab5ff069ab16aa4f63" => :sierra
    sha256 "1a77fae74e84bbf8a5d2f49faf1a548d7aaf57fe2b85737a009143eb85bff333" => :el_capitan
    sha256 "27eca42a5917f791f1a7797575faa3a1952481ffe02295f4dcdcfc04028cd1f9" => :yosemite
    sha256 "2f648859da057200b6f056d45f4041a8e055049b5123b9ded4fdd76967f3dd28" => :mavericks
    sha256 "8072477f15c69a336a63cb86c75610ab6e1b1d11eadb9b05244a4f565abf6b79" => :mountain_lion
  end

  depends_on "pkg-config" => :build
  depends_on "glib"
  depends_on "gobject-introspection"

  def install
    if build.devel?
      inreplace "src/meson.build", "'-Wl,-Bsymbolic-functions'", "" 
      mkdir "build" do
        system "meson", "--prefix=#{prefix}", "-Denable-introspection=true", "-Denable-gobject-types=true", ".."
        system "ninja"
        system "ninja", "test"
        system "ninja", "install"
      end
    else 
      system "./configure", "--disable-debug",
                            "--disable-dependency-tracking",
                            "--disable-silent-rules",
                            "--prefix=#{prefix}"
      system "make"
      system "make", "check"
      system "make", "install"
    end
  end

  test do
    (testpath/"test.c").write <<-EOS.undent
      #include <graphene-gobject.h>

      int main(int argc, char *argv[]) {
      GType type = graphene_point_get_type();
        return 0;
      }
    EOS
    gettext = Formula["gettext"]
    glib = Formula["glib"]
    flags = %W[
      -I#{gettext.opt_include}
      -I#{glib.opt_include}/glib-2.0
      -I#{glib.opt_lib}/glib-2.0/include
      -I#{include}/graphene-1.0
      -I#{lib}/graphene-1.0/include
      -L#{lib}
      -lgraphene-1.0
    ]
    system ENV.cc, "test.c", "-o", "test", *flags
    system "./test"
  end
end
````

The build itself was subsequently started as:

````
brew install graphene --devel -v
````

### Operating system in use

Mac OS X El Capitan 10.11.6

### SIMD implementation in use

No idea sorry.

I noticed that your Travis-CI configuration explicitly excludes the gobject-introspection build: is there are particular reason for this? Also, would it be a good idea to add a Travis-CI Mac OS X build to the yaml file? I could add a PR for this.

Thanks for looking into this and best wishes for 2017!

**Comment by ebassi** [comment]
This is a toolchain issue on your side:

```
/usr/local/Cellar/glib/2.50.2/include/glib-2.0/glib/gtypes.h:423:3: error: '_GStaticAssertCompileTimeAssertion_0' declared as an array with a negative size
  G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It means `unsigned long long` has a different size that `guint64`. It also has nothing to do with Graphene, as that static assertion comes from GLib. I don't know anything about Brew, and I don't have a macOS machine to test things on any more, so I'm afraid you'll have to do the detective work.

At least for a while, you can also still use Autotools to build Graphene.

I disable GObject Introspection inside the continuous integration because the packages provided by Travis are not new enough to build the Graphene introspection — I should spend some time into creating a Docker image and using that to do CI.

**Comment by tschoonj** [comment]
I managed to get rid of

````
/usr/local/Cellar/glib/2.50.2/include/glib-2.0/glib/gtypes.h:423:3: error: '_GStaticAssertCompileTimeAssertion_0' declared as an array with a negative size
  G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
````

but the other ones remain. It appears to be some kind of Homebrew issue related to me running Xcode 8.2.1 on El Capitan. I will upgrade to Sierra in a bit and see if that changes things.

**Comment by tschoonj** [comment]
For the Linux Travis-CI build: have you tried fetching the latest gobject-introspection package and compiling it from scratch before starting the graphene build? I end up doing this kind of thing often on the Ubuntu Trusty images.

The Mac OS X Travis-CI images use Homebrew which (usually) has the last version of the dependencies so that may be easy to set up.

**Comment by ebassi** [comment]
@tschoonj Building an updated gobject-introspection usually requires an updated glib, which may end up requiring new dependencies as well. Building everything would make the CI pass longer. Additionally, Travis has fairly old compilers, which have their own bugs (especially when it comes to floating point and SSE instructions).

As I said, the proper solution would be to invest some time in making a Docker image based off of a recent version of Debian or Fedora, and then testing against that.

**Comment by tschoonj** [comment]
I have managed to get rid of the syntax errors, which were caused by Homebrew setting the SDKROOT environment variable. Now I am left with this:

````
[64/65] 'Generating Graphene-1.0.gir with a custom command.'
FAILED: src/Graphene-1.0.gir 
'/usr/local/bin/g-ir-scanner' '../src/graphene-box.h' '../src/graphene-euler.h' '../src/graphene-frustum.h' '../src/graphene-macros.h' '../src/graphene-matrix.h' '../src/graphene-plane.h' '../src/graphene-point.h' '../src/graphene-point3d.h' '../src/graphene-quad.h' '../src/graphene-quaternion.h' '../src/graphene-ray.h' '../src/graphene-rect.h' '../src/graphene-size.h' '../src/graphene-sphere.h' '../src/graphene-triangle.h' '../src/graphene-types.h' '../src/graphene-vec2.h' '../src/graphene-vec3.h' '../src/graphene-vec4.h' '../src/graphene-version-macros.h' '../src/graphene-gobject.h' '../src/graphene-alloc.c' '../src/graphene-box.c' '../src/graphene-euler.c' '../src/graphene-frustum.c' '../src/graphene-matrix.c' '../src/graphene-plane.c' '../src/graphene-point.c' '../src/graphene-point3d.c' '../src/graphene-quad.c' '../src/graphene-quaternion.c' '../src/graphene-ray.c' '../src/graphene-rect.c' '../src/graphene-size.c' '../src/graphene-sphere.c' '../src/graphene-triangle.c' '../src/graphene-vectors.c' '../src/graphene-gobject.c' '-D_REENTRANT' '-I/usr/local/Cellar/gobject-introspection/1.50.0/include/gobject-introspection-1.0' '-I/usr/local/Cellar/glib/2.50.2/include/glib-2.0' '-I/usr/local/Cellar/glib/2.50.2/lib/glib-2.0/include' '-I/usr/local/opt/gettext/include' '-I/usr/local/Cellar/pcre/8.39/include' '-I/usr/local/Cellar/libffi/3.0.13/lib/libffi-3.0.13/include' '--no-libtool' '--namespace=Graphene' '--nsversion=1.0' '--warn-all' '--output' 'src/Graphene-1.0.gir' '--identifier-filter-cmd=/Users/schoon/Library/Caches/Homebrew/graphene-1.5.2/src/identfilter.py' '--c-include=graphene-gobject.h' '--accept-unprefixed' '-DGRAPHENE_COMPILATION' '-v' '--cflags-begin' '-I/Users/schoon/Library/Caches/Homebrew/graphene-1.5.2/src' '-I/Users/schoon/Library/Caches/Homebrew/graphene-1.5.2/build/src' '--cflags-end'  '-I/Users/schoon/Library/Caches/Homebrew/graphene-1.5.2/src' '-I/Users/schoon/Library/Caches/Homebrew/graphene-1.5.2/build/src' '--include=GObject-2.0' '--symbol-prefix=graphene' '--identifier-prefix=Graphene' '--pkg-export=graphene-gobject-1.0' '-I/usr/local/opt/gettext/include' '-I/usr/local/Cellar/glib/2.50.2/include/glib-2.0' '-I/usr/local/Cellar/pcre/8.39/include' '-I/usr/local/Cellar/glib/2.50.2/lib/glib-2.0/include' '-L/Users/schoon/Library/Caches/Homebrew/graphene-1.5.2/build/src' '-lm' '-lglib-2.0' '-L/usr/local/opt/gettext/lib' '-lintl' '-L/usr/local/Cellar/glib/2.50.2/lib' '-lgobject-2.0' '--library' 'graphene-1.0'
ERROR: can't resolve libraries to shared libraries: m
ninja: build stopped: subcommand failed.
````

I have tried `export LIBS=-L/usr/lib` as well as adding `'--library-path=/usr/lib'` to `gir_extra_args` in src/meson.build but neither worked 😢 

Any thoughts?

**Comment by ebassi** [comment]
This looks like mesonbuild/meson#1060 which is needed a fix in gobject-introspection as well.

**Comment by ebassi** [comment]
See also issue #82.

**Comment by tschoonj** [comment]
Thanks for the quick reply.

Looks like the patch is already in gobject-introspection's master branch, so I guess I will have to wait now until a next release is made of both gobject-introspection and meson.

**Comment by ignatenkobrain** [comment]
@tschoonj meson 0.37.x contains this patch already, so only gobject-introspection ;)

**Comment by tschoonj** [comment]
I can confirm that the error goes away when using gobject-introspection master and glib 2.51.0.

Many thanks!
